[package]
name = "yak-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0" }
log = { version = "0.4.20" }
reqwest = { version = "0.11.23", features = ["blocking"] }
shellexpand = { version = "2.1" }
url = { version = "2.5.0" }
